name: Test Workflow

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f3003502@ds.study.iitm.ac.in
        run: echo "Hello, world!"
